### ISSUE TITLE
A mistake in assignment 2 q3_nature.py 

### ISSUE THREAD

**Issue by AZdet** [Observerspy/CS234#1]
relu activation is missing in the DNN.[nature paper](https://storage.googleapis.com/deepmind-data/assets/papers/DeepMindNature14236Paper.pdf)

**Comment by Observerspy** [comment]
In tensorflow.contrib.layers relu activation is the default activation function of conv2d() and fully_connected().

**Comment by AZdet** [comment]
Sorry, I am new to this API. I suppose it is similar to tf.layers but it is not.  Thanks for your reply.
